In [1]:
# Ref: https://gepettoweb.laas.fr/doc/stack-of-tasks/pinocchio/master/doxygen-html/md_doc_d-practical-exercises_1-directgeom.html
import numpy as np

In the following, we will use numpy Matrix class to represent matrices and vectors. In numpy, vectors simply are matrices with one column. See the following example.

In [2]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])  # Define a 2x4 matrix
b = np.zeros([4, 1])  # Define a 4 vector (ie a 4x1 matrix) initialized with 0
c = A @ b             # Obtain c by multiplying A by b.

In [4]:
c

array([[0.],
       [0.]])

In [5]:
# A@b is short for np.matmul(A, b)
np.matmul(A, b)

array([[0.],
       [0.]])

A bunch of useful functions are packaged in the utils of pinocchio

In [2]:
import pinocchio as pin
from pinocchio.utils import *

In [3]:
eye(6) # Return a 6x6 identity matrix

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [4]:
zero(6) # Return a 6x1 vector

array([0., 0., 0., 0., 0., 0.])

In [5]:
zero([6, 4]) # Return a zero 6x4 matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
rand(6) # Random 6x1 vector

array([0.00690261, 0.14532178, 0.03182638, 0.12346563, 0.19839164,
       0.1594906 ])

In [8]:
isapprox(zero(6), rand(6)) # Test epsilon equality

False

In [10]:
mprint(rand([6, 3])) # Matlab-style print

ans  = 

Columns 0 through 2

   0.77419    0.36897    0.60408   
   0.63311    0.61072    0.68282   
   0.69528    0.04197    0.24451   
   0.65259    0.18608    0.83258   
   0.87498    0.10087    0.66836   
   0.23852    0.83815    0.48142   



In [17]:
# More: https://math.stackexchange.com/questions/2248413/skew-symmetric-matrix-of-vector
pin.skew(rand(3)) # Skew "cross-product" 3x3 matrix from a 3x1 vector

array([[ 0.        , -0.3209502 ,  0.49453487],
       [ 0.3209502 ,  0.        , -0.08465227],
       [-0.49453487,  0.08465227,  0.        ]])

In [21]:
# More: https://www.mathsisfun.com/algebra/vectors-cross-product.html
# Dot(cross) product gives you a projection of one vector onto another. It gives you the cosine of the angle between two vectors.
np.cross(rand(3), rand(3))     # Cross product of R^3

array([-0.20696998,  0.14222342,  0.26695387])

Specific classes are defined to represent objects of , and . Rigid displacements, elements of , are represented by the class SE3.

In [22]:
R = eye(3)
p = zero(3)

In [26]:
M0 = pin.SE3(R, p)
M0

  R =
1 0 0
0 1 0
0 0 1
  p = 0 0 0

In [30]:
M = pin.SE3.Random()
M

  R =
-0.271423  0.440685 -0.855644
-0.745813  0.465628  0.476397
 0.608353  0.767455  0.202286
  p =  0.213938 -0.967399 -0.514226

In [32]:
M.translation = p
M.rotation = R
M

  R =
1 0 0
0 1 0
0 0 1
  p = 0 0 0

Skip the Spatial velocities and forces part to save time