In [1]:
# load the model first
# Ref: https://gepettoweb.laas.fr/doc/stack-of-tasks/pinocchio/master/doxygen-html/md_doc_b_examples_a_model.html#autotoc_md33

import pinocchio as pin
urdf_file_path = r'robot_description/inspirehand_R/urdf/R_inspire.urdf'
# Load the model from urdf file
model = pin.buildModelFromUrdf(urdf_file_path)

The robot model is available in (robot)model. It contains the names of all the robot joint names, the kinematic tree parents (i.e. the graph of parents, 0 being the root and having no parents), the position of the current joint in the parent coordinate frame jointPosition, the mass, inertia and center-of-gravity position of all the bodies (condensed in a spatial inertia 6x6 matrix) inertias and the gravity of the associated world gravity. All these functions are documented and are available in the correponding class dictionnary

In [5]:
for name, function in model.__class__.__dict__.items():
    print(' **** %s: %s' % (name, function.__doc__))

 **** __module__: str(object='') -> str
str(bytes_or_buffer[, encoding[, errors]]) -> str

Create a new string object from the given object. If encoding or
errors is specified, then the object must expose a data buffer
that will be decoded using the given encoding and error handler.
Otherwise, returns the result of object.__str__() (if defined)
or repr(object).
encoding defaults to sys.getdefaultencoding().
errors defaults to 'strict'.
 **** __doc__: str(object='') -> str
str(bytes_or_buffer[, encoding[, errors]]) -> str

Create a new string object from the given object. If encoding or
errors is specified, then the object must expose a data buffer
that will be decoded using the given encoding and error handler.
Otherwise, returns the result of object.__str__() (if defined)
or repr(object).
encoding defaults to sys.getdefaultencoding().
errors defaults to 'strict'.
 **** __reduce__: None
 **** __init__: 
__init__( (object)self) -> None :
    Default constructor. Constructs an empty mode

In [6]:
# print joint names
for i in range(0, model.njoints):
    print(model.names[i])

universe
R_index_proximal_joint
R_index_intermediate_joint
R_middle_proximal_joint
R_middle_intermediate_joint
R_pinky_proximal_joint
R_pinky_intermediate_joint
R_ring_proximal_joint
R_ring_intermediate_joint
R_thumb_proximal_yaw_joint
R_thumb_proximal_pitch_joint
R_thumb_intermediate_joint
R_thumb_distal_joint


Similarly, the robot data are available in robot.data. All the variables allocated by the classical rigid-body dynamics algorithms are stored in robot.data and are available through the python wrapping. Similarly to the model object, the function are documented and are available from the class dictionnary. The most useful in the following will be the placement of the frame associated which each joint output stored in robot.data.oMi.

For example, the robot end effector corresponds to the output of the last joint, called wrist_1_joint. The ID of the joint in the joint list can be recovered from its name, and then used to access its placement:

In [14]:
data = model.createData()

In [36]:
# Get index of end effector
 
idx = model.getJointId('R_index_proximal_joint')

q = model.joints[idx]
# Compute and get the placement of joint number idx
#placement = robot.placement(q, idx)

# Be carreful, Python always returns references to values.
# You can often .copy() the object to avoid side effects
# Only get the placement
placement = data.oMi[idx].copy()


NameError: name 'robot' is not defined

In [16]:
placement

  R =
1 0 0
0 1 0
0 0 1
  p = 0 0 0

Finally, some recurring datas (used in Model and Data) have been wrapped to functions in some python shortcuts, also available in RomeoWrapper:

    The size of the robot configuration is given by nq.
    The dimension of its tangent space (velocity) is nv.
    The index of a joint in the tree can be accessed from its name by index (see above).
    The classical algorithms are also binded: com, Jcom, mass, biais, joint gravity, position and velocity of each joint.

In [32]:
from pinocchio.utils import zero, rand
import numpy as np
# q = zero(model.q)
# v = rand(model.nv)
model.nq
model.nv
placement = data.oMi[idx].copy()
# model.com(q)  # Compute the robot center of mass.
# model.placement(q, 3)  # Compute the placement of joint 3


array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.])

In [35]:
q = pin.neutral(model)
q

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])